### ISSUE TITLE
this is a question(not an issue) when will you be done with this?

### ISSUE THREAD

**Issue by easella** [acuaro-codes/cindr#2]
when you will be done with this website?My school blocks everything so please. although I found many proxy websites they do not work with many games such as wiziz io, diep io, mope io, wings io, leevz io, tilefall io, krunker io, zombs io, agar io, and taming io.

**Comment by Pers0n-dev** [comment]
@easella i have seen you around titanium network. want some proxys?? Pers0n-dev@yandex.com

**Comment by easella** [comment]
yeah sure.

**Comment by Pers0n-dev** [comment]
i found some...
https://drowningfish.gq/
https://liberty-v1.bridgeproxy.repl.co/
https://online-dictionary.ruralanemone.repl.co/
https://uedu.gq/
https://unblockering.ga/
https://subwoofersounds.ga/
https://quiteafancyemerald.com/
https://fluffycows.herokuapp.com/
https://wwwdotcom.herokuapp.com/
https://humanflavoredsoap.aizah72.repl.co/
https://flyingstar.herokuapp.com/
https://www.mikelime.design/
https://potentialgravel.ml/
http://bt-apt.herokuapp.com/
https://leadershipwing.biz/
https://wopolice.ml/
https://errorthrone.ga/

**Comment by easella** [comment]
any more proxy sites that you know of? That are hosted on heroku, repl.co, glitch.me, or codesandbox.io?

**Comment by Pers0n-dev** [comment]
i will get more soon

**Comment by easella** [comment]
Please I need more! 
I need one that works with wings io,zombs io, and wiziz io
It has to be hosted on codesandbox,repl.co,glitch.me,or heroku.

**Comment by Pers0n-dev** [comment]
ok @easella 
https://conclusivetech.com/
alloyproxy.design
https://galaxyservice.cf/
https://diamond-phoenix.herokuapp.com/
https://interactivemark.cf/
https://mr-dillon-s-resources.herokuapp.com/
https://willowsea.me/
https://drowningfish.gq/
https://liberty4all.gq/
https://holyunblockerpublic--epicloudygamer.repl.co/
https://proxiro-laboratories.gq/
https://www.incog.icu/
https://grammarfiles.net/
https://phproxy.herokuapp.com/
https://womginx.synricha.org/
https://redwastheimposter.herokuapp.com/
https://nickel.ml/
https://surfshop.cf/
https://billnyewiki.cf/
https://springtime.ml/
https://say-no-to-censorship.gq/
https://tuckers.tech/
https://stopcheckingmyhistory.herokuapp.com/
https://dog200.cf/
https://salt-faithful-peanut.glitch.me/
https://boomermath.netlify.app/
https://billnyewiki.cf/
https://ridgethread.icu/
http://sitting-dog.herokuapp.com/
https://beachball.live/
https://void-net.herokuapp.com/
https://turboschools.ml/
https://amogone.cf/
https://dairyfarms.ml/
https://safesearch.ml/

**Comment by Pers0n-dev** [comment]
i would try a bypass what filter do you have??

**Comment by easella** [comment]
contentkeeper

**Comment by easella** [comment]
oh yeah and the admins at my school blocked womginx.synricha.org

**Comment by Pers0n-dev** [comment]
task manager blocked?

**Comment by easella** [comment]
yes

**Comment by Pers0n-dev** [comment]
Ok heres a bypass
1. Go to the website chrome://extensions

2. Turn on Developer Modewith the toggle in the right hand cornr

3. Find your contentkeeper

4. Click background page in blue

5. In inspect then console console

6. Put in this code: window.close()

**Comment by easella** [comment]
developer mode is disabled

**Comment by easella** [comment]
they also blocked inspect tool

**Comment by easella** [comment]
https://salt-faithful-peanut.glitch.me/ does not work. 
![image](https://user-images.githubusercontent.com/74786054/114610360-cd9e3d00-9c6d-11eb-93c9-92a2e4a830e2.png)

**Comment by Pers0n-dev** [comment]
is this allowed?? https://chrome.google.com/webstore/detail/learning-ally-audiobooks/gdicnpbaekbefjanokchpfhnaphfnphl

**Comment by easella** [comment]
they blocked all chrome extensions

**Comment by Pers0n-dev** [comment]
this one too?

**Comment by easella** [comment]
yeah

**Comment by Pers0n-dev** [comment]
do you have the zoom app?

**Comment by easella** [comment]
yeah

**Comment by Pers0n-dev** [comment]
What you have to do is open the Zoom extension (assuming you are not currently in a meeting), and then click “Sign In,” and then “Sign in with Google.” You will then need to click where it leads you to “Create Account.” From there, click “Sign in instead.” Then click the blue text that reads “Learn More.” Now you should be in the Google Chrome Help center, but still in the Zoom extension. Click the three horizontal lines in the top left corner, then go to the “Privacy Policy” page. Finally, scroll all the way to the very bottom of that page and click the tiny link in the bottom left corner that reads “Google.”

That’s all! Search anything you want and have fun playing any game, chatting with friends, or browsing any social media website. This should work on any school chromebook, but unfortunately it will not work on school wifi if you happen to be on campus. But if you are at home and your parents have not enabled any filters on the wifi, this will work.

**Comment by easella** [comment]
ok.

**Comment by Pers0n-dev** [comment]
does it work

**Comment by easella** [comment]
can you provide me a systemya proxy demo?

**Comment by easella** [comment]
yeah

**Comment by easella** [comment]
but I want one through the browser

**Comment by Pers0n-dev** [comment]
wha??

**Comment by easella** [comment]
I mean through chrome browser. I have a games site and I want to add more games.

**Comment by Pers0n-dev** [comment]
you want games?

**Comment by easella** [comment]
yeah

**Comment by Pers0n-dev** [comment]
any game?? like this https://int3.github.io/open-syobon-action.js/

**Comment by easella** [comment]
i mean io games

**Comment by Pers0n-dev** [comment]
https://www.google.com/search?q=io+games&rlz=1CAICRP_enUS947&oq=io+games&aqs=chrome..69i57j69i60.2514j0j7&sourceid=chrome&ie=UTF-8&safe=active&ssui=on

**Comment by easella** [comment]
they are all blocked.

**Comment by Pers0n-dev** [comment]
use a proxy

**Comment by easella** [comment]
I need a systemya proxy deployed to heroku. Can you deploy one please?

**Comment by Pers0n-dev** [comment]
i dont think it works

**Comment by Pers0n-dev** [comment]
there is some .io games here https://sites.google.com/site/unblockedgameswtf

**Comment by easella** [comment]
please try at least?

**Comment by Pers0n-dev** [comment]
ok

**Comment by easella** [comment]
tell me if you get it working.

**Comment by Pers0n-dev** [comment]
sure

**Comment by Pers0n-dev** [comment]
bouncy dudes.io
https://google-opensocial.googleusercontent.com/gadgets/ifr?url=https://sites.google.com/site/s024n7m8/bouncy-dudes-io.xml&quot

Paper.io 2
https://www-ig-opensocial.googleusercontent.com/gadgets/ifr?url=https://sites.google.com/site/paperio3unblocked/paperio2.xml&quot

Paint.io
https://www-ig-opensocial.googleusercontent.com/gadgets/ifr?url=https://sites.google.com/site/drunkenduel/paintio.xml&quot

**Comment by easella** [comment]
can you get wings io?

**Comment by Pers0n-dev** [comment]
idk i will try

**Comment by easella** [comment]
please!
also get wiziz io and zombs io

**Comment by Pers0n-dev** [comment]
i try

**Comment by Pers0n-dev** [comment]
https://medium.com/@a99io/wings-io-wings-io-unblocked-6997ef2de016

**Comment by Pers0n-dev** [comment]
wiziz.io works with system ya

**Comment by easella** [comment]
fix systemya.please deploy it to heroku

**Comment by Pers0n-dev** [comment]
im not a dev

**Comment by easella** [comment]
simply deploy it to heroku

**Comment by Pers0n-dev** [comment]
ok

**Comment by Pers0n-dev** [comment]
what should it be called?

**Comment by Pers0n-dev** [comment]
not working... https://easella.herokuapp.com/

**Comment by Pers0n-dev** [comment]
repl also not working

**Comment by easella** [comment]
sysye.herokuapp.com

**Comment by Pers0n-dev** [comment]
yes

**Comment by easella** [comment]
ok deploy the app please.

**Comment by Pers0n-dev** [comment]
i did it not work

**Comment by easella** [comment]
can you find an unblocking wiziz io on google sites.
By the way, iframes do not work as a bypass for my school settings

**Comment by Pers0n-dev** [comment]
https://replit.com/@ledlamp89/firefox

**Comment by easella** [comment]
to laggy

**Comment by Pers0n-dev** [comment]
in chrome os settings is linux or playstore blocked?

**Comment by easella** [comment]
yeah

**Comment by Pers0n-dev** [comment]
System ya chatbox
https://c.mathbot.xyz/app/
temp email https://www.emailondeck.com/

**Comment by easella** [comment]
it is blocked

**Comment by Pers0n-dev** [comment]
https://c.holyunblockerurl.url/app

EXAMPLE: https://c.graduate.cf/app/

**Comment by easella** [comment]
they are blocked

**Comment by acuaro-codes** [comment]
Hey! Sorry, wasn't on github for a while.

Currently I am working on the proxy, it should be done in a few weeks at max, thanks for checking in :)

**Comment by easella** [comment]
and can you make it work with wings io and wiziz io & deploy it to heroku?

**Comment by easella** [comment]
can you at least try to make it work with krunker io, diep io, leevz io, taming io, and zombs io?

**Comment by acuaro-codes** [comment]
Sure, I'll try my best @easella

**Comment by easella** [comment]
please.

**Comment by easella** [comment]
hey try my games site that I made: [click here](https://games.awdrgyjil1234.repl.co/)
